export LANG=en_US.UTF-8
export EDITOR=ed
export VISUAL=ed

typeset -U path
path=("$HOME/.local/bin" $path)
export PATH

# Rust
if [[ -r "$HOME/.cargo/env" ]]; then
	. "$HOME/.cargo/env"
fi

if [[ -r "$HOME/.zshenv_local" ]]; then
	. "$HOME/.zshenv_local"
fi
