# p10k instant prompt, keep first
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# User configuration

export LANG=en_US.UTF-8
export REPORTTIME=10

# Programs / PATH
export PATH="$HOME/.local/bin:$PATH"
export EDITOR=ed

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    git
    rust
    zoxide
)
[[ -r "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

# zoxide
eval "$(zoxide init zsh)"

# Rust
. "$HOME/.cargo/env"

# Aliases
alias tmp='cd $(mktemp -d)'
alias ls='eza'

# Prompt
[[ -r "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize prompt, run `p10k configure` or edit ~/.omp/wt/p10k-83581a9/home/p10k.zsh.
[[ ! -f ~/.omp/wt/p10k-83581a9/home/p10k.zsh ]] || source ~/.omp/wt/p10k-83581a9/home/p10k.zsh
