# User configuration

export LANG=en_US.UTF-8
export REPORTTIME=10

# Programs / PATH
export PATH="$HOME/.local/bin:$PATH"
export EDITOR=ed

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
    git
    rust
    zoxide
)
[[ -r "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

# zoxide
eval "$(zoxide init zsh)"

# Rust
. "$HOME/.cargo/env"

# Aliases
alias tmp='cd $(mktemp -d)'
alias ls='eza'