source = ~/.config/hypr/theme.conf

general {
	hide_cursor = true
	ignore_empty_input = true
	fail_timeout = 1000
}

auth {
	fingerprint:enabled = true
}

animations {
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 2, linear
	animation = fadeOut, 1, 1, linear
}

background {
	monitor = 
	color = $background
	path = ~/.config/hypr/assets/wallpaper.jpeg
	blur_passes = 3
}

input-field {
	monitor = 
	size = 800, 80
	position = 0, 0
	halign = center
	valign = center

	inner_color = $base
	outer_color = $accent
	outline_thickness = 3
	
	font_family = $font_family_monospace
	font_color = $bright_text

	placeholder_text = password
	check_color = $accent_secondary
	fail_text = $FAIL ($ATTEMPTS)
	
	rounding = $rounding_small
	shadow_passes = 2
	fade_on_empty = true
}